#!/usr/bin/env bash
#
#  truenorthd The TrueNorth Core server.
#
#
# chkconfig: 345 80 20
# description: truenorthd
# processname: truenorthd
#

# Source function library.
. /etc/init.d/functions

# you can override defaults in /etc/sysconfig/truenorthd, see below
if [ -f /etc/sysconfig/truenorthd ]; then
        . /etc/sysconfig/truenorthd
fi

RETVAL=0

prog=truenorthd
# you can override the lockfile via TRUENORTHD_LOCKFILE in /etc/sysconfig/truenorthd
lockfile=${TRUENORTHD_LOCKFILE-/var/lock/subsys/truenorthd}

# truenorthd defaults to /usr/bin/truenorthd, override with TRUENORTHD_BIN
truenorthd=${TRUENORTHD_BIN-/usr/bin/truenorthd}

# truenorthd opts default to -disablewallet, override with TRUENORTHD_OPTS
truenorthd_opts=${TRUENORTHD_OPTS--disablewallet}

start() {
    echo -n $"Starting $prog: "
    daemon $DAEMONOPTS $truenorthd $truenorthd_opts
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -t600
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status $prog
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: service $prog {start|stop|status|restart}"
        exit 1
        ;;
esac
