description "TrueNorth Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env TRUENORTHD_BIN="/usr/bin/truenorthd"
env TRUENORTHD_USER="truenorth"
env TRUENORTHD_GROUP="truenorth"
env TRUENORTHD_PIDDIR="/var/run/truenorthd"
# upstart can't handle variables constructed with other variables
env TRUENORTHD_PIDFILE="/var/run/truenorthd/truenorthd.pid"
env TRUENORTHD_CONFIGFILE="/etc/truenorth/truenorth.conf"
env TRUENORTHD_DATADIR="/var/lib/truenorthd"

expect fork

respawn
respawn limit 5 120
kill timeout 600

pre-start script
    # this will catch non-existent config files
    # truenorthd will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$TRUENORTHD_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run bitcoind."
        echo "The setting must appear in $TRUENORTHD_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following "
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"Bitcoin Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$TRUENORTHD_PIDDIR"
    chmod 0755 "$TRUENORTHD_PIDDIR"
    chown $TRUENORTHD_USER:$TRUENORTHD_GROUP "$TRUENORTHD_PIDDIR"
    chown $TRUENORTHD_USER:$TRUENORTHD_GROUP "$TRUENORTHD_CONFIGFILE"
    chmod 0660 "$TRUENORTHD_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$TRUENORTHD_PIDFILE" \
    --chuid $TRUENORTHD_USER:$TRUENORTHD_GROUP \
    --exec "$TRUENORTHD_BIN" \
    -- \
    -pid="$TRUENORTHD_PIDFILE" \
    -conf="$TRUENORTHD_CONFIGFILE" \
    -datadir="$TRUENORTHD_DATADIR" \
    -disablewallet \
    -daemon

